name: spark
title: Apache Spark
icon: spark

services:
- name: master
  title: Spark master
  service: spark-master
  required: true
  main: true
  workloads:
  - name: main
    containers:
    - name: spark-master
      resources:
        request:
          cpu: 500
          memory: 1024
        limit:
          cpu: 1000
          memory: 2048
- name: worker
  title: Spark worker
  service: spark-worker
  required: true
  replicas: 1
  links:
  - name: master
    service: master
  workloads:
  - name: main
    containers:
    - name: spark-worker
      resources:
        request:
          cpu: 1000
          memory: 2048
        limit:
          cpu: 2000
          memory: 4096
